version: '3'

x-spark-common: &spark-common
  image: bitnami/spark:latest
  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/input:/opt/airflow/input
    - ${AIRFLOW_PROJ_DIR:-.}/output:/opt/airflow/output
    - ${AIRFLOW_PROJ_DIR:-.}/intermediate:/opt/airflow/intermediate
    - ${AIRFLOW_PROJ_DIR:-.}/src:/opt/airflow/src
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
  networks:
    - new_net

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/input:/opt/airflow/input
    - ${AIRFLOW_PROJ_DIR:-.}/output:/opt/airflow/output
    - ${AIRFLOW_PROJ_DIR:-.}/intermediate:/opt/airflow/intermediate
    - ${AIRFLOW_PROJ_DIR:-.}/src:/opt/airflow/src
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
  depends_on:
    - postgres
  networks:
    - new_net

services:
  spark-master:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"

  spark-worker:
    <<: *spark-common
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077

  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - new_net

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - scheduler

  scheduler:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --firstname Sergey --lastname Gutman --role Admin --email sergutman4@gmail.com --password admin && airflow scheduler"

networks:
  new_net:
